# Generated by Django 5.2.13 on 2026-04-16 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='brand',
            new_name='branch',
        ),
    ]
